version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  build:
    commands:
      - echo Building...
      - cd $CODEBUILD_SRC_DIR/go-discord-app
      - go build main.go
artifacts:
  secondary-artifacts:
    golang_artifacts:
      base-directory: go-discord-app
      files:
        - main
